package:
  name: tardigrade_hydra
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target tardigrade_hydra tardigrade_hydra_umat
    - cmake --install . --prefix ${PREFIX}
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - {{ compiler('cxx') }}
    - eigen >=3.3.7
    - tardigrade_error_tools>=0.4
    - tardigrade_vector_tools>=0.5.4
    - tardigrade_constitutive_tools>=0.7.2
    - tardigrade_stress_tools
    - tardigrade_solver_tools
    - tardigrade_abaqus_tools>=0.4
    - boost >=1.59  # TODO: Separate the package/test configuration to make BOOST an optional build dependency
    - setuptools_scm >=6.2
    - libcxx <16  # [osx]
  host:
    - {{ compiler('cxx') }}
    - python
    - cmake >=3.18
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
    - libcxx <16  # [osx]
  run:
    - {{ compiler('cxx') }}
    - eigen >=3.3.7
    - tardigrade_error_tools>=0.4
    - tardigrade_vector_tools>=0.5.4
    - tardigrade_constitutive_tools>=0.7.2
    - tardigrade_stress_tools
    - tardigrade_solver_tools
    - tardigrade_abaqus_tools>=0.4

test:
  requires:
    - cmake >=3.18
    - boost >=1.59
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_tardigrade_hydra.cpp
    - src/cpp/tests/test_tardigrade_hydraMicromorphic.cpp
    - src/cpp/tests/test_tardigrade_hydraLinearElasticity.cpp
    - src/cpp/tests/test_tardigrade_hydraMicromorphicLinearElasticity.cpp
    - src/cpp/tests/test_tardigrade_hydraLinearViscoelasticity.cpp
    - src/cpp/tests/test_tardigrade_hydraThermalExpansion.cpp
    - src/cpp/tests/test_tardigrade_hydraPeryznaViscoplasticity.cpp
    - src/cpp/tests/test_tardigrade_hydraPeryznaViscodamage.cpp
    - src/cpp/tests/test_tardigrade_hydraMicromorphicDruckerPragerPlasticity.cpp
    - src/abaqus/CMakeLists.txt
    - src/abaqus/single_element_c3d8.inp
    - src/abaqus/tests/CMakeLists.txt
    - src/abaqus/tests/test_abaqus.sh
  commands:
    - mkdir build-tests
    - cd build-tests
    - cmake .. -DCMAKE_BUILD_TYPE=conda-test
    - cmake --build . --verbose
    - ctest --output-on-failure
