package:
  name: cpp_stub
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - tree
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target cpp_stub cpp_stub_umat
    - cmake --install . --prefix $PREFIX
  ignore_run_exports:
    - python_abi

requirements:
  # TODO: need to pin the Python version, or at least build a variant to match (3.8.3)
  build:
    - python {{ python }}
    - {{ compiler('cxx') }}
    - cmake >=3.17
    - doxygen
    - eigen >=3.3.7
    - error_tools
    - vector_tools
    - abaqus_tools
  host:
    - python
    - eigen >=3.3.7
  run:
    - python
    - {{ compiler('cxx') }}
    - eigen >=3.3.7
    - error_tools
    - vector_tools
    - abaqus_tools

test:
  requires:
    - cmake >=3.17
    - boost >=1.59
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_cpp_stub.cpp
  commands:
    - tree
    - mkdir build-tests
    - cd build-tests
    - cmake .. -DCMAKE_BUILD_TYPE=test
    - cmake --build . --target test_cpp_stub --verbose
    - ctest -R test_cpp_stub
