package:
  name: cpp_stub
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target cpp_stub cpp_stub_umat
  script_env:
    - VERSION
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python {{ python }}
    - git
    - boost
    - doxygen
    - cmake >=3.14
  host:
    - python
  run:
    - python
    - boost

test:
  requires:
    - cmake
  source_files:
    - cpp_stub/tests/*.py
  commands:
    - mkdir build
    - cd build
    - cmake --build . --target test_cpp_stub abaqus_integration_test
    - ctest --output-on-failure
