workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - test
  - deploy

before_script:
  - source activate_w13pythonenv.sh
  - conda info 

test_build:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    GIT_STRATEGY: clone
  script:
    - ./BUILD.sh
    - ./TEST.sh
  artifacts:
    when: always
    paths:
      - build/results.tex
  tags:
    - sstelmo-shell-aea

deploy_build:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script: ./CD.sh
  tags:
    - sstelmo-shell-aea
  only:
    - master
    - dev

# It MUST be called pages
pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - rm -rf public && mkdir -p public
    - cp docs/html/index.html public
    # Every documentation version must be re-built for *every* gitlab-pages job execution
    # Reference: https://gitlab.com/gitlab-org/gitlab/-/issues/33822
    - git fetch origin
    - git branch -a
    - documentation_branches="master dev"
    - |
        for ref in ${documentation_branches}; do
            git checkout $ref
            git reset --hard origin/$ref
            mkdir -p public/$ref/doxygen
            ./BUILD.sh
            cp -r build/docs/sphinx/html/* public/$ref
            cp -r build/docs/doxygen/html/* public/$ref/doxygen
        done
  artifacts:
    paths:
      # It MUST be called public
      - public
  tags:
    - sstelmo-shell-aea
  only:
    - master
    - dev
