workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - test
  - deploy

before_script:
  # Set the AEA compute environment deployment directory by host
  - aea_projects="/projects"
  - if [[ $(hostname) == sn-rfe?.lanl.gov ]] || [[ $(hostname) == sn???.localdomain ]]; then aea_projects="/usr/projects/ea"; fi
  - aea_deploy_directory="${aea_projects}/python"
  - aea_conda_channel="${aea_deploy_directory}/aea-conda"
  # Pick the AEA compute environment according to Gitlab CI environment
  - environment="aea-release"
  - if [[ ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} == dev ]] || [[ ${CI_COMMIT_BRANCH} == dev ]]; then environment='aea-beta'; fi
  # Add the AEA compute environment modules to MODULEPATH and load
  - module use --append "${aea_deploy_directory}/modulefiles"
  - echo "${environment}"
  - module help "${environment}"
  - module load "${environment}"
  # Environment troubleshooting information
  - echo $PATH
  - echo $PYTHONPATH
  - echo $MANPATH
  - echo $LD_LIBRARY_PATH
  - conda info
  - env | grep -i proxy

test_build:
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  variables:
    GIT_STRATEGY: clone
  script:
    - ./BUILD.sh
    - ./TEST.sh
  artifacts:
    when: always
    paths:
      - build/results.tex
  tags:
    - sstelmo-shell-aea

deploy_build:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script: ./CD.sh
  tags:
    - sstelmo-shell-aea
  only:
    - master
    - dev

# It MUST be called pages
pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  script:
    - rm -rf public && mkdir -p public
    - cp docs/html/index.html public
    # Every documentation version must be re-built for *every* gitlab-pages job execution
    # Reference: https://gitlab.com/gitlab-org/gitlab/-/issues/33822
    - git fetch origin
    - git branch -a
    - documentation_branches="master dev"
    - |
        for ref in ${documentation_branches}; do
            git checkout $ref
            git reset --hard origin/$ref
            mkdir -p public/$ref/doxygen
            ./BUILD.sh
            cp -r build/docs/sphinx/html/* public/$ref
            cp -r build/docs/doxygen/html/* public/$ref/doxygen
        done
  artifacts:
    paths:
      # It MUST be called public
      - public
  tags:
    - sstelmo-shell-aea
  only:
    - master
    - dev
